### ISSUE TITLE
Error on Node

### ISSUE THREAD

**Issue by kuselan84** [coolaj86/rrecurjs#7]
It's not working on node js. 
Code:
var rrecur = Rrecur.create({
    dtstart: {
        zoneless: Rrecur.toLocaleISOString(new Date(2014,06,21, 10,30,0), "GMT-0400 (EDT)")
        , locale: "GMT-0400 (EDT)"

    }
    , rrule: null
}, new Date());

Error:
/Users/kuselan/WebstormProjects/aries/node_modules/rrecur/rrecur.js:381
    Object.keys(orig).forEach(function (k) {
           ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Function.Rrecur.stringify (/Users/kuselan/WebstormProjects/aries/node_modules/rrecur/rrecur.js:381:12)
    at Rrecur.proto.init (/Users/kuselan/WebstormProjects/aries/node_modules/rrecur/rrecur-iterator.js:191:31)
    at new Rrecur (/Users/kuselan/WebstormProjects/aries/node_modules/rrecur/rrecur.js:58:8)
    at Function.Rrecur (/Users/kuselan/WebstormProjects/aries/node_modules/rrecur/rrecur.js:55:14)
    at Object.<anonymous> (/Users/kuselan/WebstormProjects/aries/rrecur.js:20:21)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)

**Comment by simonstewart** [comment]
Getting the same thing.
